// <auto-generated />
namespace UniversityManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addDepartmentUpdate1Tbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDepartmentUpdate1Tbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201601312029300_addDepartmentUpdate1Tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
